### ISSUE TITLE
anli task

### ISSUE THREAD

**Issue by Gio-CCHAN** [Heidelberg-NLP/MHKA#3]
could you please provide some instruction on how to perform anli task?

**Comment by debjitpaul** [comment]
Hi,
Can you please elaborate on your question?
Check this out:  https://github.com/Heidelberg-NLP/MHKA/tree/main/src/model

**Comment by Gio-CCHAN** [comment]
Thanks for the prompt reply!
i tried to change the task_name to anli to run this task on the anli dataset, but it seems that there is only swag_processor in the util file. so could you give some instruction on fine-tuning the model on anli dataset?

**Comment by debjitpaul** [comment]
So, now I have updated the code. Did you download the anli data? This is a bit of old code, so you need to download the anli data and mention the path of the data in the run.sh file as DATA_DIR='data_path'

**Comment by Gio-CCHAN** [comment]
Hi,
I just checked the changes. sorry for bothering that question, I thought a new processor is needed for the anli task.
